djangoQuiz/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('quiz', views.quiz,name='quiz'),
]

quiz/models.py
from django.db import models

# Create your models here.
class Questions(models.Model):
    question = models.CharField(max_length=200)
    op1 = models.CharField(max_length=200)
    op2 = models.CharField(max_length=200)
    op3 = models.CharField(max_length=200)
    op4 = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)


    def __str__(self):
        return self.question

quiz/views.py
import imp
from django.shortcuts import render
from django.http import HttpResponse
from quiz.models import *

# Create your views here.
def index(request):
    return render(request, 'quiz/index.html')

def quiz(request):
    questions = Questions.objects.all()
    if request.method == "POST":
        score = 0
        total = 0
        correct = 0
        incorrect = 0
        for q in questions:
            total+=1
            if q.answer == request.POST.get(q.question):
                score+=10
                correct+=1
            else:
                incorrect+=1
        percentage = (score/ (total*10)) * 100
        context = {
            'score': score,
            'correct': correct,
            'incorrect': incorrect,
            'percentage': percentage
        }
        return render(request, 'quiz/results.html', context)

    else:
        return render(request, 'quiz/quiz.html',{'questions':questions})

templates/quiz/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Basic Quiz</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <body>
       {% block content%}
       {% endblock %}
    </body>
</html>

templates/quiz/index.html
{% extends 'quiz/base.html' %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="container bg-dark p-5 text-light">
            <h1 class="display-4">Welcome to Basic Quiz</h1>
            <hr>
            <p>This quiz has ten (10) questions. Each question has one possible answer. Choose the correct
                answer and at the end of the quiz you'll receive your score and percentage. Good Luck!
            </p>
            <a class="btn btn-primary" href="{% url 'quiz:quiz' %}" role="button">Start Quiz</a>
        </div>
    </div>
{% endblock %}

templates/quiz/quiz.html
{% extends 'quiz/base.html' %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="container bg-dark p-5 text-light">
            <h1 class="display-4">Quiz</h1>
            <hr>
            <form method="POST">
                {% csrf_token %}
                {% for q in questions %}
                <div class="form-group">
                    <label for="question"> {{ forloop.counter }}. {{ q.question }}</label>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input type="radio" id="gRadio1" class="form-check-input" name="{{ q.question}}" value="{{ q.op1 }}">
                        <label for="qRadio1" class="form-check-label"> {{ q.op1 }}</label>
                    </div>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input type="radio" id="gRadio2" class="form-check-input" name="{{ q.question}}" value="{{ q.op2 }}">
                        <label for="qRadio2" class="form-check-label"> {{ q.op2 }}</label>
                    </div>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input type="radio" id="gRadio3" class="form-check-input" name="{{ q.question}}" value="{{ q.op3 }}">
                        <label for="qRadio3" class="form-check-label"> {{ q.op3 }}</label>
                    </div>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input type="radio" id="gRadio4" class="form-check-input" name="{{ q.question}}" value="{{ q.op4 }}">
                        <label for="qRadio4" class="form-check-label"> {{ q.op4 }}</label>
                    </div>
                </div>
                <br>
                {% endfor %}
                <br>
                <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/quiz/results.html
{% extends 'quiz/base.html' %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="container bg-dark p-5 text-light">
            <h1 class="display-4">Results</h1>
            <hr>
            
            <div class="card bq-dark">
                <div class="card-body bg-dark">
                    <h3>Grade: {% if percentage >= 50 %} <span style="color: green;">PASS</span> {% else %} <span style="color: red;">FAIL</span> {% endif %}</h3>
                    <p>Score: {{ score }}</p>
                    <p>Correct: {{ correct }}</p>
                    <p>Incorrect: {{ incorrect }}</p>
                    <p>Percentage: {{ percentage }}%</p>
                </div>
            </div>
            <hr>
            <a class="btn btn-primary" href="{% url 'index' %}" role="button">Take Quiz Again</a>
        </div>
    </div>
{% endblock %}